
import React, { useEffect, useState } from 'react'

import Head from 'next/head'
import SuperTokensReact from 'supertokens-auth-react'
import * as SuperTokensConfig from '../../config/frontendConfig'
import Session from 'supertokens-auth-react/recipe/session'
import { redirectToAuth } from 'supertokens-auth-react/recipe/thirdpartyemailpassword'
import { AppProvider } from '../components/context'
import theme from '../assets/theme'
import { ThemeProvider, createTheme } from "@mui/material/styles";
import CssBaseline from '@mui/material/CssBaseline'
import { getUser } from '../lib/api/user'


//Supertokens logic
async function initNode() {
  const supertokensNode = await import('supertokens-node')
  const { backendConfig } = await import('../../config/backendConfig')
  supertokensNode.init(backendConfig())
}

if (typeof window !== 'undefined') {
  SuperTokensReact.init(SuperTokensConfig.frontendConfig())
} else {
  initNode().catch(console.error)
}

function App({ Component, pageProps }) {

  const [isLogged, setIsLogged] = React.useState({ state: false, admin: false, authId: '' })
  //Guarda productos que se van añádiendo o quitando del carrito
  const [cart, setCart] = React.useState([])


  //Supertokens logic
  useEffect(() => {
    async function doRefresh() {
      if (pageProps.fromSupertokens === 'needs-refresh') {
        if (await Session.attemptRefreshingSession()) {
          location.reload()
        } else {
          // user has been logged out
          redirectToAuth()
        }
      }
    }
    doRefresh()

  }, [pageProps.fromSupertokens])

  useEffect(() => {
    const storedCart = JSON.parse(localStorage.getItem("cart"));
    storedCart && setCart(storedCart)
    const checkSession = async () => {
      //Si existe una sesión activa, la promesa devuelve true
      // setIsLogged(await Session.doesSessionExist())
      const state = await Session.doesSessionExist()
      /**
       * Si el userId del usuario logado tiene asignado el rol de administrador, admin=true
       * userdId es el identificador de usuario en la bdd de supertokens. Se obtiene y se renombra a authID
       * authId es un identificador de usuario en la bdd de la app. Permite relacionar el usuario logado
       * con supertokens con su perfil de usuario en la bdd de la app.
       */
      const { admin, userId: authId } = state && await Session.getAccessTokenPayloadSecurely()
      const info = state && await Session.getAccessTokenPayloadSecurely()
      const user = await getUser(authId)
      //Convierte el valor admin en booleano porque, cuando no es true, devuelve undefined
      setIsLogged({ state, admin: !!admin, authId: authId ? authId : '', user: user })
    }
    checkSession()
  }, [])

  useEffect(() => {
    localStorage.setItem("cart", JSON.stringify(cart))

  }, [cart])


  if (pageProps.fromSupertokens === 'needs-refresh') {
    return null
  }

  const appProps = { authId: isLogged.authId, isLogged, setIsLogged, cart, setCart }
  pageProps.authId = isLogged.authId
  pageProps.isLogged = { ...isLogged }

  return (
    <>
      <Head>
        <meta name="google-site-verification" content="zbvzA8Zrgps5RRh86gp797a6HsdJkBRhP5vY0K0KkjQ" />
        <title>Sevimatic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppProvider {...appProps}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Component {...pageProps} />
        </ThemeProvider >
      </AppProvider>
    </>
  )
}

export default App

